
spring:
  datasource:
    url: jdbc:sqlite:data/iot_messages.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: never
      continue-on-error: true
  thymeleaf:
    cache: false

# MyBatis 설정
mybatis:
  mapper-locations: classpath:sql/mapper/IotMessageMapper.xml
  type-aliases-package: com.daedong.agmtms.metry.dto
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080


aws:
  iot:
    endpoint: a1vopgopgy3eh3-ats.iot.ap-northeast-2.amazonaws.com
    clientId: metry-local-daedong-agmtms
    certificateFile: certs/MZC-Test-Thing-01.cert.pem
    privateKeyFile: certs/MZC-Test-Thing-01.private.key
    rootCAFile: certs/AmazonRootCA1.pem
    topics: DDTM/TRIP/+,DDTM/INIT/+,DDTM/DTC/+,DDTM/RO/+,DDTM/ACC/+,DDTM/MAP/+   # ✅ 쉼표로 구분된 문자열로 변경